apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bilf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bilf
    app.kubernetes.io/part-of: ci10t-777-0089-app
  name: devfile-sample-bilf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bilf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bilf
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0089-tenant/ci10t-777-0089-app/devfile-sample-bilf@sha256:95dd2a8ef1afd1d1d1e40a820db25e4635c067e058af58871ca22c80344324b2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
